### ISSUE TITLE
直接启动dubbo-sample会导致qos address绑定重复的问题

### ISSUE THREAD

**Issue by Stellar1999** [apache/dubbo-samples#1003]
如果直接启动basic的sample-api,会因为qos-server 地址重复(22222).无法在本地同时启动cousmer和provider
是否考虑优化一下？换掉一个不同地址

**Comment by AlbumenJ** [comment]
Would you pls submit a PR?

**Comment by Stellar1999** [comment]
I noticed that QoS address occupation does not prevent the service from starting. However, I still want to submit a pull request to suggest a solution to fix this error.

**Comment by Stellar1999** [comment]
However, I am still unable to start the consumer successfully for some reason. The error log is as follows:
`18:43:35.602 [main] INFO org.apache.dubbo.remoting.transport.AbstractClient -  [DUBBO] Start NettyClient /26.26.26.1 connect to the server /26.26.26.1:20880, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:35.616 [main] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
18:43:35.616 [main] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
18:43:35.617 [main] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@312b34e3
18:43:35.617 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
18:43:35.617 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
18:43:35.617 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
18:43:35.617 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
18:43:35.617 [main] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
18:43:40.585 [NettyClientWorker-4-1] INFO org.apache.dubbo.remoting.transport.netty4.NettyClientHandler -  [DUBBO] The connection of /26.26.26.1:56849 -> /26.26.26.1:20880 is disconnected., dubbo version: 3.2.6, current host: 26.26.26.1
18:43:40.585 [DubboClientHandler-thread-1] DEBUG org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol -  [DUBBO] disconnected from /26.26.26.1:20880,url:dubbo://26.26.26.1:20880/org.apache.dubbo.samples.api.GreetingsService?application=first-dubbo-consumer&background=false&category=providers,configurators,routers&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&environment=product&executor-management-mode=isolation&file-cache=true&generic=false&heartbeat=60000&interface=org.apache.dubbo.samples.api.GreetingsService&methods=sayHi&pid=93224&prefer.serialization=fastjson2,hessian2&qos.port=22222&release=3.2.6&service-name-mapping=true&side=consumer&sticky=false&unloadClusterRelated=false, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:40.630 [main] WARN org.apache.dubbo.rpc.proxy.InvokerInvocationHandler -  [DUBBO] [Dubbo-Consumer] execute service first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:dubbo#getMetadataInfo cost 5018.884584 ms, this invocation almost (maybe already) timeout. Timeout: 5000ms
invocation context:
path=org.apache.dubbo.metadata.MetadataService;
version=1.0.0;
timeout=5000;
group=first-dubbo-provider;
thread info: 
Start time: 70867101946791
+-[ Offset: 0.000000ms; Usage: 5018.884584ms, 100% ] Receive request. Client invoke begin. ServiceKey: first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 MethodName:getMetadataInfo, dubbo version: 3.2.6, current host: 26.26.26.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
18:43:40.630 [main] INFO org.apache.dubbo.remoting.transport.netty4.NettyChannel -  [DUBBO] Close netty channel [id: 0x64550eae, L:/26.26.26.1:56852 - R:/26.26.26.1:20880], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:40.631 [NettyClientWorker-4-2] INFO org.apache.dubbo.remoting.transport.netty4.NettyClientHandler -  [DUBBO] The connection of /26.26.26.1:56852 -> /26.26.26.1:20880 is disconnected., dubbo version: 3.2.6, current host: 26.26.26.1
18:43:40.631 [DubboClientHandler-thread-1] DEBUG org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol -  [DUBBO] disconnected from /26.26.26.1:20880,url:dubbo://26.26.26.1:20880/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=first-dubbo-provider&heartbeat=60000&port=20880&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:40.632 [main] ERROR org.apache.dubbo.registry.client.metadata.MetadataUtils -  [DUBBO] Failed to get app metadata for revision 550ec3dde0f1965fc38637be434a67d9 for type local from instance 26.26.26.1:20880, dubbo version: 3.2.6, current host: 26.26.26.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: getMetadataInfo, provider: dubbo://26.26.26.1:20880/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=first-dubbo-provider&port=20880&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2023-10-13 18:43:35.614, end time: 2023-10-13 18:43:40.627, client elapsed: 12 ms, server elapsed: 5001 ms, timeout: 5000 ms, request: Request [id=-6830257342520368652, version=2.0.2, twoWay=true, event=false, broken=false, mPayload=0, data=RpcInvocation [methodName=getMetadataInfo, parameterTypes=[class java.lang.String]]], channel: /26.26.26.1:56852 -> /26.26.26.1:20880
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:294)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:86)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:320)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:225)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:187)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:88)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:184)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:140)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:629)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:440)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:246)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:76)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:249)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:594)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:564)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:546)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:110)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:80)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:620)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:466)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:353)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:132)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:495)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:475)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:176)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:728)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:692)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:665)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:227)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:216)
	at org.apache.dubbo.samples.client.Application.main(Application.java:45)
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2023-10-13 18:43:35.614, end time: 2023-10-13 18:43:40.627, client elapsed: 12 ms, server elapsed: 5001 ms, timeout: 5000 ms, request: Request [id=-6830257342520368652, version=2.0.2, twoWay=true, event=false, broken=false, mPayload=0, data=RpcInvocation [methodName=getMetadataInfo, parameterTypes=[class java.lang.String]]], channel: /26.26.26.1:56852 -> /26.26.26.1:20880
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:218)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	... 51 common frames omitted
Caused by: org.apache.dubbo.remoting.TimeoutException: Waiting server-side response timeout by scan timer. start time: 2023-10-13 18:43:35.614, end time: 2023-10-13 18:43:40.627, client elapsed: 12 ms, server elapsed: 5001 ms, timeout: 5000 ms, request: Request [id=-6830257342520368652, version=2.0.2, twoWay=true, event=false, broken=false, mPayload=0, data=RpcInvocation [methodName=getMetadataInfo, parameterTypes=[class java.lang.String]]], channel: /26.26.26.1:56852 -> /26.26.26.1:20880
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:245)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:200)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.notifyTimeout(DefaultFuture.java:321)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture$TimeoutCheckTask.lambda$run$0(DefaultFuture.java:308)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:152)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:77)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:205)
	... 52 common frames omitted
18:43:41.635 [main] DEBUG org.apache.dubbo.registry.client.metadata.MetadataUtils -  [DUBBO] Instance 26.26.26.1:20880 is using metadata type local, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:41.636 [main] INFO org.apache.dubbo.rpc.model.ModuleModel -  [DUBBO] Dynamically registering consumer model first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 into model Dubbo Module[1.1.0], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:41.639 [main] INFO org.apache.dubbo.remoting.transport.AbstractClient -  [DUBBO] Successfully connect to server /26.26.26.1:20880 from NettyClient 26.26.26.1 using dubbo version 3.2.6, channel is NettyChannel [channel=[id: 0x01dc4004, L:/26.26.26.1:56857 - R:/26.26.26.1:20880]], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:41.639 [NettyClientWorker-4-3] INFO org.apache.dubbo.remoting.transport.netty4.NettyClientHandler -  [DUBBO] The connection of /26.26.26.1:56857 -> /26.26.26.1:20880 is established., dubbo version: 3.2.6, current host: 26.26.26.1
18:43:41.640 [main] INFO org.apache.dubbo.remoting.transport.AbstractClient -  [DUBBO] Start NettyClient /26.26.26.1 connect to the server /26.26.26.1:20880, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:46.649 [main] WARN org.apache.dubbo.rpc.proxy.InvokerInvocationHandler -  [DUBBO] [Dubbo-Consumer] execute service first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:dubbo#getMetadataInfo cost 5008.600458 ms, this invocation almost (maybe already) timeout. Timeout: 5000ms
invocation context:
path=org.apache.dubbo.metadata.MetadataService;
version=1.0.0;
timeout=5000;
group=first-dubbo-provider;
thread info: 
Start time: 70873132151458
+-[ Offset: 0.000000ms; Usage: 5008.600458ms, 100% ] Receive request. Client invoke begin. ServiceKey: first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 MethodName:getMetadataInfo, dubbo version: 3.2.6, current host: 26.26.26.1, error code: 3-4. This may be caused by , go to https://dubbo.apache.org/faq/3/4 to find instructions. 
18:43:46.662 [main] INFO org.apache.dubbo.remoting.transport.netty4.NettyChannel -  [DUBBO] Close netty channel [id: 0x01dc4004, L:/26.26.26.1:56857 - R:/26.26.26.1:20880], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:46.663 [NettyClientWorker-4-3] INFO org.apache.dubbo.remoting.transport.netty4.NettyClientHandler -  [DUBBO] The connection of /26.26.26.1:56857 -> /26.26.26.1:20880 is disconnected., dubbo version: 3.2.6, current host: 26.26.26.1
18:43:46.663 [main] ERROR org.apache.dubbo.registry.client.metadata.MetadataUtils -  [DUBBO] Failed to get app metadata for revision 550ec3dde0f1965fc38637be434a67d9 for type local from instance 26.26.26.1:20880, dubbo version: 3.2.6, current host: 26.26.26.1, error code: 1-39. This may be caused by , go to https://dubbo.apache.org/faq/1/39 to find instructions. 
org.apache.dubbo.rpc.RpcException: Invoke remote method timeout. method: getMetadataInfo, provider: dubbo://26.26.26.1:20880/org.apache.dubbo.metadata.MetadataService?connections=1&corethreads=2&dubbo=2.0.2&group=first-dubbo-provider&port=20880&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, cause: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:304)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:190)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:61)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:75)
	at org.apache.dubbo.metadata.MetadataServiceDubboProxy0.getMetadataInfo(MetadataServiceDubboProxy0.java)
	at org.apache.dubbo.registry.client.metadata.MetadataUtils.getRemoteMetadata(MetadataUtils.java:173)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.lambda$getRemoteMetadata$2(AbstractServiceDiscovery.java:229)
	at org.apache.dubbo.metrics.event.MetricsEventBus.post(MetricsEventBus.java:86)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.getRemoteMetadata(AbstractServiceDiscovery.java:228)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.lambda$doOnEvent$2(ServiceInstancesChangedListener.java:162)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.doOnEvent(ServiceInstancesChangedListener.java:162)
	at org.apache.dubbo.registry.client.event.listener.ServiceInstancesChangedListener.onEvent(ServiceInstancesChangedListener.java:116)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribeURLs(ServiceDiscoveryRegistry.java:320)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.doSubscribe(ServiceDiscoveryRegistry.java:225)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.subscribe(ServiceDiscoveryRegistry.java:187)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:88)
	at org.apache.dubbo.registry.integration.DynamicDirectory.subscribe(DynamicDirectory.java:184)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryDirectory.subscribe(ServiceDiscoveryRegistryDirectory.java:140)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doCreateInvoker(RegistryProtocol.java:629)
	at org.apache.dubbo.registry.integration.InterfaceCompatibleRegistryProtocol.getServiceDiscoveryInvoker(InterfaceCompatibleRegistryProtocol.java:65)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.refreshServiceDiscoveryInvoker(MigrationInvoker.java:440)
	at org.apache.dubbo.registry.client.migration.MigrationInvoker.migrateToApplicationFirstInvoker(MigrationInvoker.java:246)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.refreshInvoker(MigrationRuleHandler.java:76)
	at org.apache.dubbo.registry.client.migration.MigrationRuleHandler.doMigrate(MigrationRuleHandler.java:60)
	at org.apache.dubbo.registry.client.migration.MigrationRuleListener.onRefer(MigrationRuleListener.java:249)
	at org.apache.dubbo.registry.integration.RegistryProtocol.interceptInvoker(RegistryProtocol.java:594)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:564)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:546)
	at org.apache.dubbo.rpc.protocol.ProtocolSecurityWrapper.refer(ProtocolSecurityWrapper.java:110)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:85)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:80)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:71)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.refer(ProtocolSerializationWrapper.java:52)
	at org.apache.dubbo.rpc.protocol.InvokerCountWrapper.refer(InvokerCountWrapper.java:48)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createInvoker(ReferenceConfig.java:620)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:466)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:353)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:238)
	at org.apache.dubbo.config.utils.SimpleReferenceCache.get(SimpleReferenceCache.java:132)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.lambda$referServices$6(DefaultModuleDeployer.java:495)
	at java.base/java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.referServices(DefaultModuleDeployer.java:475)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:176)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:728)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:692)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:665)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:227)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:216)
	at org.apache.dubbo.samples.client.Application.main(Application.java:45)
Caused by: java.util.concurrent.TimeoutException: Timeout after 5000ms waiting for result.
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:207)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:287)
	... 51 common frames omitted
18:43:46.663 [DubboClientHandler-thread-1] DEBUG org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol -  [DUBBO] disconnected from /26.26.26.1:20880,url:dubbo://26.26.26.1:20880/org.apache.dubbo.metadata.MetadataService?codec=dubbo&connections=1&corethreads=2&dubbo=2.0.2&group=first-dubbo-provider&heartbeat=60000&port=20880&prefer.serialization=fastjson2,hessian2&protocol=dubbo&release=3.2.6&retries=0&side=consumer&threadpool=cached&threads=100&timeout=5000&version=1.0.0, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:46.663 [main] DEBUG org.apache.dubbo.registry.client.AbstractServiceDiscovery -  [DUBBO] Retry the 1 times to get metadata for revision=550ec3dde0f1965fc38637be434a67d9, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:47.672 [main] DEBUG org.apache.dubbo.registry.client.metadata.MetadataUtils -  [DUBBO] Instance 26.26.26.1:20880 is using metadata type local, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:47.673 [main] INFO org.apache.dubbo.rpc.model.ModuleModel -  [DUBBO] Dynamically registering consumer model first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0 into model Dubbo Module[1.1.0], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:47.677 [NettyClientWorker-4-4] INFO org.apache.dubbo.remoting.transport.netty4.NettyClientHandler -  [DUBBO] The connection of /26.26.26.1:56862 -> /26.26.26.1:20880 is established., dubbo version: 3.2.6, current host: 26.26.26.1
18:43:47.677 [main] INFO org.apache.dubbo.remoting.transport.AbstractClient -  [DUBBO] Successfully connect to server /26.26.26.1:20880 from NettyClient 26.26.26.1 using dubbo version 3.2.6, channel is NettyChannel [channel=[id: 0xe66960d5, L:/26.26.26.1:56862 - R:/26.26.26.1:20880]], dubbo version: 3.2.6, current host: 26.26.26.1
18:43:47.677 [main] INFO org.apache.dubbo.remoting.transport.AbstractClient -  [DUBBO] Start NettyClient /26.26.26.1 connect to the server /26.26.26.1:20880, dubbo version: 3.2.6, current host: 26.26.26.1
18:43:48.900 [main-SendThread(127.0.0.1:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for session id: 0x10004228935000a after 3ms.
18:43:48.900 [main-SendThread(127.0.0.1:2181)] DEBUG org.apache.zookeeper.ClientCnxn - Got ping response for session id: 0x100042289350009 after 1ms.
18:43:52.687 [main] WARN org.apache.dubbo.rpc.proxy.InvokerInvocationHandler -  [DUBBO] [Dubbo-Consumer] execute service first-dubbo-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:dubbo#getMetadataInfo cost 5008.790333 ms, this invocation almost (maybe already) timeout. Timeout: 5000ms
invocation context:
path=org.apache.dubbo.metadata.MetadataService;
version=1.0.0;
timeout=5000;
group=first-dubbo-provider;
thread info: 
Start time: 70879169790083`

**Comment by AlbumenJ** [comment]
Pls check if you have configured SOCKS5 proxy

**Comment by Stellar1999** [comment]
> Pls check if you have configured SOCKS5 proxy

After checking, I think there hasn't been any configuration done for SOCKS5.

**Comment by AlbumenJ** [comment]
Is `26.26.26.1` your local ip?

**Comment by Stellar1999** [comment]
> Is `26.26.26.1` your local ip?

No, I found it. It looks like my VPN IP. After I closed it, Dubbo seems to work correctly, but I don't understand why it is connecting to this IP.

**Comment by AlbumenJ** [comment]
> > Is `26.26.26.1` your local ip?
> 
> No, I found it. It looks like my VPN IP. After I closed it, Dubbo seems to work correctly, but I don't understand why it is connecting to this IP.

This is depended on your routing table and network interface order.

**Comment by Stellar1999** [comment]
> > > Is `26.26.26.1` your local ip?
> > 
> > 
> > No, I found it. It looks like my VPN IP. After I closed it, Dubbo seems to work correctly, but I don't understand why it is connecting to this IP.
> 
> This is depended on your routing table and network interface order.

OK,Thanks~
