### ISSUE TITLE
dubbo-samples-native-image runs failed.

### ISSUE THREAD

**Issue by imgoby** [apache/dubbo-samples#1007]
dubbo-samples-native-image runs failed.

how to resolve it?

`

2023-10-20T15:52:49.381+08:00 ERROR [dubbo-samples-nativeimage-provider,,] 16112 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:org.apache.dubbo.nativeimage.DemoService::': Instantiation of supplied bean failed
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1220)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293)
	at org.apache.dubbo.nativeimage.provider.NativeDemoProviderApplication.main(NativeDemoProviderApplication.java:33)
Caused by: java.lang.IllegalStateException: Failed to create adaptive instance: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:750)
	at org.apache.dubbo.config.ServiceConfig.postProcessAfterScopeModelChanged(ServiceConfig.java:181)
	at org.apache.dubbo.config.AbstractConfig.setScopeModel(AbstractConfig.java:428)
	at org.apache.dubbo.config.AbstractConfig.<init>(AbstractConfig.java:129)
	at org.apache.dubbo.config.AbstractMethodConfig.<init>(AbstractMethodConfig.java:110)
	at org.apache.dubbo.config.AbstractInterfaceConfig.<init>(AbstractInterfaceConfig.java:207)
	at org.apache.dubbo.config.AbstractServiceConfig.<init>(AbstractServiceConfig.java:162)
	at org.apache.dubbo.config.ServiceConfigBase.<init>(ServiceConfigBase.java:92)
	at org.apache.dubbo.config.ServiceConfig.<init>(ServiceConfig.java:167)
	at org.apache.dubbo.config.spring.ServiceBean.<init>(ServiceBean.java:58)
	at org.apache.dubbo.config.spring.ServiceBean__BeanDefinitions.lambda$getDemoServiceInstanceSupplier$0(ServiceBean__BeanDefinitions.java:20)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68)
	at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:202)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:210)
	at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.obtainInstanceFromSupplier(DefaultListableBeanFactory.java:947)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1214)
	... 17 common frames omitted
Caused by: java.lang.IllegalStateException: Can't create adaptive extension interface org.apache.dubbo.rpc.Protocol, cause: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1399)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtension(ExtensionLoader.java:745)
	... 36 common frames omitted
Caused by: java.lang.IllegalStateException: No adaptive method exist on extension org.apache.dubbo.rpc.Protocol, refuse to create the adaptive class!
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:105)
	at org.apache.dubbo.common.extension.AdaptiveClassCodeGenerator.generate(AdaptiveClassCodeGenerator.java:95)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtensionClass(ExtensionLoader.java:1421)
	at org.apache.dubbo.common.extension.ExtensionLoader.getAdaptiveExtensionClass(ExtensionLoader.java:1408)
	at org.apache.dubbo.common.extension.ExtensionLoader.createAdaptiveExtension(ExtensionLoader.java:1391)
	... 37 common frames omitted`

**Comment by AlbumenJ** [comment]
@CrazyHZM PTAL

**Comment by oxsean** [comment]
https://cn.dubbo.apache.org/zh-cn/blog/2023/06/28/%E8%B5%B0%E5%90%91-native-%E5%8C%96springdubbo-aot-%E6%8A%80%E6%9C%AF%E7%A4%BA%E4%BE%8B%E4%B8%8E%E5%8E%9F%E7%90%86%E8%AE%B2%E8%A7%A3/#%E7%AC%AC%E5%85%AD%E6%AD%A5%E7%BC%96%E8%AF%91
Please using
`mvn clean install -P native native:compile -Dmaven.test.skip=true`
to build

**Comment by imgoby** [comment]
Thank you. I run successfully.
Previously, I used to use this command： mvn -Pnative native:compile
Now, I use the command you suggested: mvn clean install -P native native:compile -Dmaven.test.skip=true  ,successfully


The difference is not significant, but for some unknown reason

**Comment by oxsean** [comment]
I think dubbo aot need generate some proxy class in maven phase process-sources, if you call native:compile direct, proxy class will not be generated.

**Comment by shellyxue** [comment]
添加下面代码到工程中，可以解决这个问题：

```
@Configuration(proxyBeanMethods = false)
@ConditionalOnClass(name = "org.apache.dubbo.rpc.Protocol$Adaptive")
@ImportRuntimeHints(DubboHintsConfiguration.CustomRuntimeHintsRegistrar.class)
public class DubboHintsConfiguration {
    public static class CustomRuntimeHintsRegistrar implements RuntimeHintsRegistrar {
        private static final String BASE_PACKAGES = "org.apache.dubbo";
        private static final String FILTER_SUFFIX = "/**/*$Adaptive.class";

        @Override
        @SuppressWarnings("unchecked")
        public void registerHints(RuntimeHints hints, @Nullable ClassLoader classLoader) {
            try {
                //注册Adaptive类对象
                ResourcePatternResolver resourcePatternResolver = new PathMatchingResourcePatternResolver();
                MetadataReaderFactory metadataReaderFactory = new CachingMetadataReaderFactory(resourcePatternResolver);

                String packageSearchPath = ResourcePatternResolver.CLASSPATH_ALL_URL_PREFIX
                        + ClassUtils.convertClassNameToResourcePath(SystemPropertyUtils.resolvePlaceholders(BASE_PACKAGES))
                        + FILTER_SUFFIX;
                Resource[] resources = resourcePatternResolver.getResources(packageSearchPath);
                Arrays.stream(resources).forEach(x -> {
                    try {
                        MetadataReader metadataReader = metadataReaderFactory.getMetadataReader(x);
                        Class<?> clazz = Class.forName(metadataReader.getClassMetadata().getClassName());
                        hints.reflection().registerType(clazz, MemberCategory.values());
                    } catch (Throwable ignored) {

                    }
                });
            } catch (Throwable ignored) {

            }

        }
    }

}
```
