### ISSUE TITLE
dubbo-samples-generic-impl-provider cannot pass travis CI

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo-samples#101]
dubbo-samples-generic-impl-provider cannot pass travis CI, but it works in local env.

```
[ERROR] testHelloAsync(org.apache.dubbo.samples.generic.call.HelloServiceIT)  Time elapsed: 0.027 s  <<< ERROR!
java.util.concurrent.ExecutionException: 
org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.rpc.RpcException: Failed to invoke remote proxy method sayHelloAsync to registry://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=generic-impl-provider&dubbo=2.0.2&export=dubbo%3A%2F%2F172.17.0.1%3A20880%2Forg.apache.dubbo.samples.generic.call.api.HelloService%3Fanyhost%3Dtrue%26application%3Dgeneric-impl-provider%26bind.ip%3D172.17.0.2%26bind.port%3D20880%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dtrue%26generic%3Dtrue%26interface%3Dorg.apache.dubbo.samples.generic.call.api.HelloService%26methods%3D*%26pid%3D1%26register%3Dtrue%26release%3D2.7.2%26side%3Dprovider%26timestamp%3D1562572679691&pid=1&registry=zookeeper&release=2.7.2&timestamp=1562572679669, cause: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
org.apache.dubbo.rpc.RpcException: Failed to invoke remote proxy method sayHelloAsync to registry://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=generic-impl-provider&dubbo=2.0.2&export=dubbo%3A%2F%2F172.17.0.1%3A20880%2Forg.apache.dubbo.samples.generic.call.api.HelloService%3Fanyhost%3Dtrue%26application%3Dgeneric-impl-provider%26bind.ip%3D172.17.0.2%26bind.port%3D20880%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dtrue%26generic%3Dtrue%26interface%3Dorg.apache.dubbo.samples.generic.call.api.HelloService%26methods%3D*%26pid%3D1%26register%3Dtrue%26release%3D2.7.2%26side%3Dprovider%26timestamp%3D1562572679691&pid=1&registry=zookeeper&release=2.7.2&timestamp=1562572679669, cause: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:107)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:48)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:96)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:148)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:150)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.dubbo.common.bytecode.NoSuchMethodException: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
	at org.apache.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	... 27 more

	at org.apache.dubbo.samples.generic.call.HelloServiceIT.testHelloAsync(HelloServiceIT.java:43)
Caused by: org.apache.dubbo.remoting.RemotingException: 
org.apache.dubbo.rpc.RpcException: Failed to invoke remote proxy method sayHelloAsync to registry://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=generic-impl-provider&dubbo=2.0.2&export=dubbo%3A%2F%2F172.17.0.1%3A20880%2Forg.apache.dubbo.samples.generic.call.api.HelloService%3Fanyhost%3Dtrue%26application%3Dgeneric-impl-provider%26bind.ip%3D172.17.0.2%26bind.port%3D20880%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dtrue%26generic%3Dtrue%26interface%3Dorg.apache.dubbo.samples.generic.call.api.HelloService%26methods%3D*%26pid%3D1%26register%3Dtrue%26release%3D2.7.2%26side%3Dprovider%26timestamp%3D1562572679691&pid=1&registry=zookeeper&release=2.7.2&timestamp=1562572679669, cause: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
org.apache.dubbo.rpc.RpcException: Failed to invoke remote proxy method sayHelloAsync to registry://127.0.0.1:2181/org.apache.dubbo.registry.RegistryService?application=generic-impl-provider&dubbo=2.0.2&export=dubbo%3A%2F%2F172.17.0.1%3A20880%2Forg.apache.dubbo.samples.generic.call.api.HelloService%3Fanyhost%3Dtrue%26application%3Dgeneric-impl-provider%26bind.ip%3D172.17.0.2%26bind.port%3D20880%26deprecated%3Dfalse%26dubbo%3D2.0.2%26dynamic%3Dtrue%26generic%3Dtrue%26interface%3Dorg.apache.dubbo.samples.generic.call.api.HelloService%26methods%3D*%26pid%3D1%26register%3Dtrue%26release%3D2.7.2%26side%3Dprovider%26timestamp%3D1562572679691&pid=1&registry=zookeeper&release=2.7.2&timestamp=1562572679669, cause: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:107)
	at org.apache.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:56)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:92)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:48)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:81)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:96)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:148)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:41)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:82)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$CallbackRegistrationInvoker.invoke(ProtocolFilterWrapper.java:150)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:152)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:102)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:193)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.dubbo.common.bytecode.NoSuchMethodException: Not found method "sayHelloAsync" in class org.apache.dubbo.samples.generic.call.impl.GenericImplOfHelloService.
	at org.apache.dubbo.common.bytecode.Wrapper0.invokeMethod(Wrapper0.java)
	at org.apache.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at org.apache.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:84)
	... 27 more
```

**Comment by complone** [comment]
I think you should configure a docker environment on the remote host and debug it on it, because the successfully packaged classes here don't seem to be automatically published in tomcat.
