### ISSUE TITLE
运行dubbo-samples-zookeeper，提示No such extension org.apache.dubbo.rpc.Protocol by name dubbo

### ISSUE THREAD

**Issue by abcgis** [apache/dubbo-samples#181]
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.rpc.Protocol by name dubbo
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:618)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:625)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:424)
	at org.apache.dubbo.config.ServiceConfig.findConfigedPorts(ServiceConfig.java:644)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:444)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:325)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:300)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:206)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$16(DubboBootstrap.java:943)
	at java.util.HashMap$Values.forEach(HashMap.java:981)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:930)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:749)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:59)
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:52)
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
	at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:33)

**Comment by chickenlj** [comment]
是不是pom里少 dubbo-protocol-dubbo 依赖
