### ISSUE TITLE
dubbo-samples-kubernetes 运行报错 consumer incorrect token

### ISSUE THREAD

**Issue by szh81128** [apache/dubbo-samples#447]
参考readme运行后
provider报错：consumer incorrect token
consumer报错：
[10/05/22 06:05:35:035 UTC] main  INFO deploy.DefaultApplicationDeployer:  [DUBBO] Dubbo Application[1.1](dubbo-samples-apiserver-consumer) is ready., dubbo version: 3.0.7, current host: 10.244.5.56
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.apache.dubbo.rpc.RpcException: Failed to invoke the method sayHello in the service org.apache.dubbo.samples.api.GreetingService. Tried 3 times of the providers [10.244.14.192:20885, 10.244.6.181:20885, 10.244.13.73:20880] (3/3) from the registry DEFAULT_MASTER_HOST:9090 on the consumer 10.244.5.56 using the dubbo version 3.0.7. Last error is: Failed to invoke remote method: sayHello, provider: DefaultServiceInstance{serviceName='dubbo-samples-apiserver-provider', host='10.244.6.181', port=20885, enabled=true, healthy=true, metadata={dubbo.metadata-service.url-params={"connections":"1","token":"259f83cc-7dec-468e-886a-25d7dab564b5","version":"1.0.0","dubbo":"2.0.2","release":"3.0.7","side":"provider","port":"20885","protocol":"dubbo"}, dubbo.endpoints=[{"port":20885,"protocol":"dubbo"}], dubbo.metadata.revision=888aeeb23126323407a6b2be95f128f0}}, service{name='org.apache.dubbo.samples.api.GreetingService',group='null',version='1.0.0',protocol='dubbo',params={side=provider, release=3.0.7, methods=sayHello, deprecated=false, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, service-name-mapping=true, version=1.0.0, generic=false, token=a11c5aa2-4a81-42f0-96c8-612ce2475a87, revision=1.0.0, metadata-service-port=20885, application=dubbo-samples-apiserver-provider, background=false, dynamic=true, anyhost=true},}, cause: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:276)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:123)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:114)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:340)
	at org.apache.dubbo.rpc.cluster.router.RouterSnapshotFilter.invoke(RouterSnapshotFilter.java:46)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:99)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.cluster.filter.support.ConsumerContextFilter.invoke(ConsumerContextFilter.java:109)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CopyOfFilterChainNode.invoke(FilterChainBuilder.java:321)
	at org.apache.dubbo.rpc.cluster.filter.FilterChainBuilder$CallbackRegistrationInvoker.invoke(FilterChainBuilder.java:193)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$ClusterFilterInvoker.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:97)
	at org.apache.dubbo.registry.client.migration.ServiceDiscoveryMigrationInvoker.invoke(ServiceDiscoveryMigrationInvoker.java:68)
	at org.apache.dubbo.rpc.proxy.InvocationUtil.invoke(InvocationUtil.java:57)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:73)
	at org.apache.dubbo.samples.api.GreetingServiceDubboProxy1.sayHello(GreetingServiceDubboProxy1.java)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy26.sayHello(Unknown Source)
	at org.apache.dubbo.samples.action.GreetingServiceConsumer.doSayHello(GreetingServiceConsumer.java:34)
	at org.apache.dubbo.samples.ConsumerBootstrap.main(ConsumerBootstrap.java:35)
	... 8 more
Caused by: java.util.concurrent.ExecutionException: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:276)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:123)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:750)

	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:195)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.waitForResultIfSync(AbstractInvoker.java:264)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:185)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invokeWithContext(AbstractClusterInvoker.java:378)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:80)
	... 33 more
Caused by: org.apache.dubbo.remoting.RemotingException: org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
org.apache.dubbo.remoting.RemotingException: Not found exported service: org.apache.dubbo.samples.api.GreetingService:1.0.0:20885 in [org.apache.dubbo.samples.api.GreetingService:1.0.0:20880, dubbo-samples-apiserver-provider/org.apache.dubbo.metadata.MetadataService:1.0.0:20885], may be version or group mismatch , channel: consumer: /10.244.5.56:40886 --> provider: /10.244.6.181:20885, message:RpcInvocation [methodName=sayHello, parameterTypes=[class java.lang.String], arguments=[], attachments={input=355, path=org.apache.dubbo.samples.api.GreetingService, remote.application=dubbo-samples-apiserver-consumer, dubbo=2.0.2, interface=org.apache.dubbo.samples.api.GreetingService, version=1.0.0, timeout=3000, token=7436e4bd-3f3d-42b8-a0ec-dc3295645243}]
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol.getInvoker(DubboProtocol.java:276)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:123)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:100)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:175)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.dubbo.common.threadlocal.InternalRunnable.run(InternalRunnable.java:41)
	at java.lang.Thread.run(Thread.java:750)

	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.doReceived(DefaultFuture.java:214)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:176)
	at org.apache.dubbo.remoting.exchange.support.DefaultFuture.received(DefaultFuture.java:164)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleResponse(HeaderExchangeHandler.java:60)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:181)
	at org.apache.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at org.apache.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:57)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor$RunnableWrapper.run(ThreadlessExecutor.java:184)
	at org.apache.dubbo.common.threadpool.ThreadlessExecutor.waitAndDrain(ThreadlessExecutor.java:103)
	at org.apache.dubbo.rpc.AsyncRpcResult.get(AsyncRpcResult.java:193)
	... 38 more
[10/05/22 06:15:32:032 UTC] Dubbo-framework-cache-refreshing-scheduler-thread-1  INFO metadata.AbstractCacheManager$CacheRefreshTask:  [DUBBO] Dumping mapping caches, latest entries 1, dubbo version: 3.0.7, current host: 10.244.5.56
[10/05/22 06:15:33:033 UTC] Dubbo-framework-cache-refreshing-scheduler-thread-1  INFO metadata.AbstractCacheManager$CacheRefreshTask:  [DUBBO] Dumping meta caches, latest entries 3, dubbo version: 3.0.7, current host: 10.244.5.56
[10/05/22 07:05:35:035 UTC] Dubbo-framework-cache-refreshing-scheduler-thread-1  INFO metadata.AbstractCacheManager$CacheRefreshTask:  [DUBBO] Dumping mapping caches, latest entries 1, dubbo version: 3.0.7, current host: 10.244.5.56
[10/05/22 07:15:36:036 UTC] Dubbo-framework-cache-refreshing-scheduler-thread-1  INFO metadata.AbstractCacheManager$CacheRefreshTask:  [DUBBO] Dumping meta caches, latest entries 3, dubbo version: 3.0.7, current host: 10.244.5.56

**Comment by szhengli** [comment]
能私下沟通下吗？邮箱是opre@163.com. 我也调[dubbo-samples-kubernetes]， consumer老是报 no provider.  谢谢

**Comment by szh811218** [comment]
> 能私下沟通下吗？邮箱是[opre@163.com](mailto:opre@163.com). 我也调[dubbo-samples-kubernetes]， consumer老是报 no provider. 谢谢

您这个情况我没碰到过。。。。。
