### ISSUE TITLE
dubbo-samples-kubernetes-dns 示例 无法打包

### ISSUE THREAD

**Issue by szhengli** [apache/dubbo-samples#508]
dubbo-samples-kubernetes-dns 示例 无法打包

        <dependency>
            <groupId>org.apache.dubbo.extensions</groupId>
            <artifactId>dubbo-registry-dns</artifactId>
            <version>1.0.2-SNAPSHOT</version>
        </dependency>
上面的依赖包不存在，改为：
<dependency>
    <groupId>org.apache.dubbo</groupId>
    <artifactId>dubbo-registry-dns</artifactId>
    <version>3.0.5</version>
</dependency>
可以打包部署后，provider启动报错：

<html>
<body>

ort=20885&methods=sayHello&pid=1&qos.accept.foreign.ip=true&qos.enable=true&release=3.1.0&revision=1.0.0&service-name-mapping=true&side=provider&timestamp=1661673684437&token=ea52d510-31fa-47e7-bd86-d60d92077274&version=1.0.0 to registry 10.43.0.10:53, dubbo version: 3.1.0, current host: 10.42.2.145
--
[28/08/22 08:01:25:025 UTC] main ERROR common.Version: [DUBBO] Duplicate class org/apache/dubbo/remoting/exchange/Exchangers.class in 2 jar [file:/app/libs/dubbo-3.1.0.jar!/org/apache/dubbo/remoting/exchange/Exchangers.class, file:/app/libs/dubbo-remoting-api-3.1.0.jar!/org/apache/dubbo/remoting/exchange/Exchangers.class], dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main ERROR common.Version: [DUBBO] Duplicate class org/apache/dubbo/remoting/Transporters.class in 2 jar [file:/app/libs/dubbo-remoting-api-3.1.0.jar!/org/apache/dubbo/remoting/Transporters.class, file:/app/libs/dubbo-3.1.0.jar!/org/apache/dubbo/remoting/Transporters.class], dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main ERROR common.Version: [DUBBO] Duplicate class org/apache/dubbo/remoting/RemotingException.class in 2 jar [file:/app/libs/dubbo-remoting-api-3.1.0.jar!/org/apache/dubbo/remoting/RemotingException.class, file:/app/libs/dubbo-3.1.0.jar!/org/apache/dubbo/remoting/RemotingException.class], dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main INFO transport.AbstractServer: [DUBBO] Start NettyServer bind /0.0.0.0:20880, export /10.42.2.145:20880, dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main ERROR deploy.DefaultModuleDeployer: [DUBBO] Dubbo Module[1.1.1] start failed: java.lang.NoClassDefFoundError: org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery, dubbo version: 3.1.0, current host: 10.42.2.145
java.lang.NoClassDefFoundError: org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.apache.dubbo.registry.dns.DNSServiceDiscoveryFactory.createDiscovery(DNSServiceDiscoveryFactory.java:26)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:394)
at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:243)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:647)
at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:625)
at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584)
at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:416)
at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:400)
at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:362)
at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:234)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:337)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:309)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.registry.client.SelfHostMetaServiceDiscovery
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 52 more
[28/08/22 08:01:25:025 UTC] main INFO metadata.ConfigurableMetadataServiceExporter: [DUBBO] Using dubbo protocol to export metadata service on port 20885, dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main INFO deploy.DefaultModuleDeployer: [DUBBO] Dubbo Module[1.1.0] is starting., dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main ERROR deploy.DefaultApplicationDeployer: [DUBBO] Dubbo Application[1.1](dubbo-samples-apiserver-provider) found failed module: Dubbo Module[1.1.1], dubbo version: 3.1.0, current host: 10.42.2.145
java.lang.NoClassDefFoundError: org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.apache.dubbo.registry.dns.DNSServiceDiscoveryFactory.createDiscovery(DNSServiceDiscoveryFactory.java:26)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:394)
at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:243)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:647)
at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:625)
at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584)
at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:416)
at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:400)
at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:362)
at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:234)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:337)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:309)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.registry.client.SelfHostMetaServiceDiscovery
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 52 more
[28/08/22 08:01:25:025 UTC] main INFO deploy.DefaultModuleDeployer: [DUBBO] Dubbo Module[1.1.0] has started., dubbo version: 3.1.0, current host: 10.42.2.145
[28/08/22 08:01:25:025 UTC] main ERROR deploy.DefaultApplicationDeployer: [DUBBO] Dubbo Application[1.1](dubbo-samples-apiserver-provider) found failed module: Dubbo Module[1.1.1], dubbo version: 3.1.0, current host: 10.42.2.145
java.lang.NoClassDefFoundError: org/apache/dubbo/registry/client/SelfHostMetaServiceDiscovery
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.apache.dubbo.registry.dns.DNSServiceDiscoveryFactory.createDiscovery(DNSServiceDiscoveryFactory.java:26)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.lambda$getServiceDiscovery$0(AbstractServiceDiscoveryFactory.java:53)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
at org.apache.dubbo.registry.client.AbstractServiceDiscoveryFactory.getServiceDiscovery(AbstractServiceDiscoveryFactory.java:53)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.getServiceDiscovery(ServiceDiscoveryRegistry.java:122)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:109)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:86)
at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:94)
at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:394)
at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:243)
at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:647)
at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:625)
at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584)
at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:416)
at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:400)
at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:362)
at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:234)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:337)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:309)
at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:111)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:100)
at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:45)
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:84)
at org.apache.dubbo.samples.ProviderBootstrap.main(ProviderBootstrap.java:33)
Caused by: java.lang.ClassNotFoundException: org.apache.dubbo.registry.client.SelfHostMetaServiceDiscovery
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 52 more
[28/08/22 08:01:25:025 UTC] main WARN config.Environment: [DUBBO] dynamicConfiguration is null , return glo

</body>
</html>

**Comment by AlbumenJ** [comment]
Will be fixed in https://github.com/apache/dubbo-spi-extensions/pull/176
