### ISSUE TITLE
 dubbo-samples-triple: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo

### ISSUE THREAD

**Issue by pioneerjxf** [apache/dubbo-samples#519]
It threw exception like below, when I started TriStubServer in dubbo-samples-triple.

[05:21:49:049] ERROR deploy.DefaultModuleDeployer:  [DUBBO] Dubbo Module[1.1.1] start failed: java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo, no related exception was found, please check whether related SPI module is missing., dubbo version: 3.0.8, current host: 192.168.1.8
java.lang.IllegalStateException: No such extension org.apache.dubbo.registry.RegistryFactory by name dubbo, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:723)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:730)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:524)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:498)
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:393)
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:242)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:641)
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:619)
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:578)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:410)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:396)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:361)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:233)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:341)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:313)
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:145)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startModules(DefaultApplicationDeployer.java:601)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.doStart(DefaultApplicationDeployer.java:565)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:538)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:224)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:214)
	at org.apache.dubbo.sample.tri.stub.TriStubServer.start(TriStubServer.java:64)
	at org.apache.dubbo.sample.tri.stub.TriStubServer.main(TriStubServer.java:43)

**Comment by AlbumenJ** [comment]
How could you startup this app? Would you please provide the parameters?

**Comment by pioneerjxf** [comment]
sorry, my fault
