### ISSUE TITLE
See "No Spring WebApplicationInitializer types detected on classpath" when run tomcat 

### ISSUE THREAD

**Issue by liubin192837** [apache/dubbo-samples#98]
Put dubbo-samples-rest-1.0-SNAPSHOT.war to ROOT.war to tomcat  and run *startup.bat*, seee this issue:
23-Jun-2019 15:42:49.808 信息 [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log No Spring WebApplicationInitializer types detected on classpath
23-Jun-2019 15:42:50.068 严重 [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Error configuring application listener of class [com.alibaba.dubbo.remoting.http.servlet.BootstrapListener]
	java.lang.ClassNotFoundException: com.alibaba.dubbo.remoting.http.servlet.BootstrapListener
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
		at org.apache.catalina.core.DefaultInstanceManager.loadClass(DefaultInstanceManager.java:546)
		at org.apache.catalina.core.DefaultInstanceManager.loadClassMaybePrivileged(DefaultInstanceManager.java:527)
		at org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:150)
		at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4692)
		at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
		at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
		at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
		at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
		at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
		at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
		at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1851)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)
23-Jun-2019 15:42:50.124 严重 [localhost-startStop-1] org.apache.catalina.core.StandardContext.listenerStart Skipped installing application listeners due to previous error(s)
23-Jun-2019 15:42:51.364 信息 [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()

**Comment by complone** [comment]
i think you can see this issue [#95](https://github.com/apache/dubbo/issues/95)

```
public class DubboShutDownListener implements ServletContextListener {

    @Override
    public void contextDestroyed(ServletContextEvent arg0){
         arg0.getServletContext().log("DubboShutDownListener.contextDestroyed called!");
        try {
            final Class protocolConfig = Class.forName("com.alibaba.dubbo.config.ProtocolConfig");

            final Method method = protocolConfig.getMethod("destroyAll");
            method.invoke(protocolConfig);
        } catch (Exception e){
             arg0.getServletContext().log("destory dubbo failed:"+e.getMessage(), e);

        }
    }

    @Override
    public void contextInitialized(ServletContextEvent arg0){
        //System.out.println("DubboShutDownListener.contextInitialized called!");
    }
}
```
